//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DmQT03Entities : DbContext
    {
        public DmQT03Entities()
            : base("name=DmQT03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<CashBill> CashBills { get; set; }
        public DbSet<CashBillDetail> CashBillDetails { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<InstallmentBill> InstallmentBills { get; set; }
        public DbSet<InstallmentBillDetail> InstallmentBillDetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
    }
}
