//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Product
    {
        public Product()
        {
            this.CashBillDetails = new HashSet<CashBillDetail>();
            this.InstallmentBillDetails = new HashSet<InstallmentBillDetail>();
        }
    
        public int ID { get; set; }
        public string ProductCode { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập Product Name")]
        [DataType(DataType.Text)]
        [StringLength(250, MinimumLength = 5)]
        public string ProductName { get; set; }

        public int ProductTypeID { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập Sale Price")]
        [DataType(DataType.Currency)]
        [Range(1, 1000000000, ErrorMessage = "Giá phải trong khoảng 1 đến 1 tỷ")]
        public int SalePrice { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập Origin Price")]
        [DataType(DataType.Currency)]
        [Range(1, 1000000000, ErrorMessage = "Giá phải trong khoảng 1 đến 1 tỷ")]
        public int OriginPrice { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập Installment Price")]
        [DataType(DataType.Currency)]
        [Range(1, 1000000000, ErrorMessage = "Giá phải trong khoảng 1 đến 1 tỷ")]
        public int InstallmentPrice { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập Quantity")]
        [Range(1, 10000, ErrorMessage = "Giá phải trong khoảng 1 đến 10000")]
        public int Quantity { get; set; }

        [StringLength(255, MinimumLength = 0)]
        public string Avatar { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        public HttpPostedFileBase ImageFile { get; set; }

        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<CashBillDetail> CashBillDetails { get; set; }
        public virtual ICollection<InstallmentBillDetail> InstallmentBillDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
